"use client";
import { useEffect, useState } from "react";
import { ArrowUpRight, BookOpen, ChevronRight, Download, FileText, LogOut, Pencil, Plus, RefreshCw, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogHeader } from "@/components/ui/dialog";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import Logo from "./logo";
import { api, conditions, type Condition, type WritingSession } from "@/lib/aware";
import { type SourceSet } from "@/lib/materials";

type Student = { username: string; condition: Condition; source_set_id: string };
type SessionSummary = WritingSession & { username: string; characters: number };
type Event = { id: string; type: string; payload: string; created: number };
type Review = { session: WritingSession & { username: string }; events: Event[]; note: string };
export type TeacherData = { students: Student[]; materials: SourceSet[]; sessions: SessionSummary[]; aiRequests: number };
const emptyMaterial: SourceSet = { id: "", title: "", prompt: "Integrate evidence from both sources, develop a defensible position, and address relevant counterarguments.", aTitle: "", aBody: "", bTitle: "", bBody: "", isDemo: false };
const words = (text: string) => text.trim() ? text.trim().split(/\s+/).length : 0;
const date = (timestamp: number) => new Date(timestamp).toLocaleString(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", second: "2-digit" });
function Choice({ label, value, options, change }: { label: string; value: string; options: { value: string; label: string }[]; change: (value: string) => void }) {
  return <Select value={value} onValueChange={change}><SelectTrigger className="teacher-select" aria-label={label}><SelectValue /></SelectTrigger><SelectContent position="popper">{options.map(option => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select>;
}
function StudentRow({ student, materials, saved }: { student: Student; materials: SourceSet[]; saved: () => Promise<void> }) {
  const [condition, setCondition] = useState(student.condition);
  const [source, setSource] = useState(student.source_set_id);
  const [status, setStatus] = useState("");
  const [busy, setBusy] = useState(false);
  async function save() { setBusy(true); setStatus(""); try { await api("teacher.assign", { username: student.username, condition, sourceSetId: source }); await saved(); setStatus("Saved for next session"); } catch (e) { setStatus((e as Error).message); } finally { setBusy(false); } }
  return <div className="student-row"><div className="student-name"><span className="user-initial">{student.username.toUpperCase()}</span><div><strong>{student.username}</strong><span>Student account</span></div></div><div><label>Interaction condition</label><Choice label={`Condition for ${student.username}`} value={condition} change={v => { setCondition(v as Condition); setStatus(""); }} options={Object.entries(conditions).map(([value, c]) => ({ value, label: c.full }))} /></div><div><label>Assigned source set</label><Choice label={`Sources for ${student.username}`} value={source} change={v => { setSource(v); setStatus(""); }} options={materials.map(m => ({ value: m.id, label: m.title }))} /></div><Button variant="outline" disabled={busy} onClick={save}>{busy ? "Saving…" : "Save assignment"}</Button>{status && <p role="status" className="assignment-status">{status}</p>}</div>;
}
function MaterialEditor({ material, onClose, onSaved }: { material: SourceSet; onClose: () => void; onSaved: () => Promise<void> }) {
  const [draft, setDraft] = useState(material);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const update = (key: keyof SourceSet, value: string | boolean) => setDraft(d => ({ ...d, [key]: value }));
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { await api("teacher.saveMaterials", { materials: draft }); await onSaved(); onClose(); } catch (e) { setError((e as Error).message); setBusy(false); } }
  return <Dialog open onOpenChange={open => { if (!open && !busy) onClose(); }}><DialogContent className="material-dialog" onInteractOutside={e => e.preventDefault()}><DialogHeader><DialogTitle>{material.id ? "Edit reading materials" : "New reading materials"}</DialogTitle><DialogDescription>One writing task, two contrasting sources. Aim for approximately 700 words per source.</DialogDescription></DialogHeader><form onSubmit={submit}>
    <div className="material-fields"><label htmlFor="task-title">Writing task / question</label><Input id="task-title" value={draft.title} maxLength={200} required onChange={e => update("title", e.target.value)} placeholder="What question should students respond to?" /><label htmlFor="task-instruction">Task instructions</label><Textarea id="task-instruction" value={draft.prompt} maxLength={2000} required onChange={e => update("prompt", e.target.value)} />
      <div className="source-edit-columns">{(["a", "b"] as const).map(side => <section key={side}><h3>Source {side.toUpperCase()}</h3><label htmlFor={`${side}-title`}>Source title</label><Input id={`${side}-title`} value={draft[`${side}Title`]} maxLength={200} required onChange={e => update(`${side}Title`, e.target.value)} /><div className="source-body-label"><label htmlFor={`${side}-body`}>Reading text</label><span>{words(draft[`${side}Body`])} words</span></div><Textarea id={`${side}-body`} value={draft[`${side}Body`]} maxLength={25000} required onChange={e => update(`${side}Body`, e.target.value)} placeholder="Paste the source text here. Include its attribution and reference." className="source-body-input" /></section>)}</div>
      <label className="demo-checkbox"><Checkbox checked={draft.isDemo} onCheckedChange={v => update("isDemo", v === true)} />Mark these as demonstration materials</label><p className="material-note">Changes apply to new writing sessions. Existing sessions retain the source version they started with.</p>{error && <p role="alert" className="error-message">{error}</p>}
    </div><div className="material-footer"><Button variant="outline" type="button" disabled={busy} onClick={onClose}>Cancel</Button><Button className="condition-button" disabled={busy}>{busy ? "Saving…" : "Save materials"}</Button></div>
  </form></DialogContent></Dialog>;
}
function SessionReview({ review, onClose }: { review: Review; onClose: () => void }) {
  const [filter, setFilter] = useState("ai");
  const [version, setVersion] = useState<{ text: string; label: string } | null>(null);
  const events = review.events.filter(e => filter === "all" || (filter === "ai" && ["ai_handoff", "ask_ai_clicked"].includes(e.type)) || (filter === "checkpoints" && e.type === "checkpoint_completed") || (filter === "versions" && e.type === "draft_saved"));
  function download() { const url = URL.createObjectURL(new Blob([JSON.stringify(review, null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = `aware-${review.session.username}-${review.session.id.slice(0, 8)}.json`; a.click(); URL.revokeObjectURL(url); }
  return <Dialog open onOpenChange={open => { if (!open) onClose(); }}><DialogContent className="review-dialog"><DialogHeader><p className="eyebrow muted">STUDENT WRITING · {review.session.username.toUpperCase()}</p><DialogTitle>{review.session.task_title || "Predictive learning analytics"}</DialogTitle><DialogDescription>{date(review.session.created)} · {review.session.status === "active" ? "In progress" : "Completed"} · {words(review.session.plain_text || "")} words</DialogDescription></DialogHeader>
    <div className="review-columns"><section className="review-draft"><div className="review-pane-heading"><h3>{version ? "Saved version" : "Latest saved writing"}</h3>{version && <Button variant="ghost" onClick={() => setVersion(null)}>Latest</Button>}</div>{version && <p className="version-date">{version.label}</p>}<div className="teacher-draft">{(version ? version.text : review.session.plain_text) || "No writing has been saved yet."}</div></section><section className="review-activity"><Tabs value={filter} onValueChange={setFilter}><TabsList><TabsTrigger value="ai">AI calls</TabsTrigger><TabsTrigger value="checkpoints">Checkpoints</TabsTrigger><TabsTrigger value="versions">Versions</TabsTrigger><TabsTrigger value="all">All</TabsTrigger></TabsList></Tabs><p className="ai-boundary">AI calls show clicks and handoffs to EdUHK GenAI. External prompts and responses are not captured.</p><div className="event-list">{events.length === 0 ? <p className="empty-events">No {filter === "ai" ? "AI calls" : "records"} in this session.</p> : events.map(event => { const data = JSON.parse(event.payload); return <article key={event.id} className="event-item"><p className="event-time">{date(event.created)}</p><h4>{({ ask_ai_clicked: "Ask AI clicked", ai_handoff: "Ask AI → EdUHK GenAI", checkpoint_completed: "Checkpoint completed", draft_saved: "Writing version saved", source_viewed: `Source ${data.source || ""} viewed`, text_selected: "Text selected", text_pasted: "Text pasted", text_copied: "Text copied", returned_to_workspace: "Returned to writing", session_completed: "Session completed" } as Record<string, string>)[event.type] || event.type}</h4>{event.type === "checkpoint_completed" && <><p>Next action: {data.next === "ai" ? "Continue to AI" : "Return to writing"}</p><dl><dt>Activity</dt><dd>{data.answers?.activity}</dd><dt>{data.condition === "appraisal" ? "Learning significance" : "Task completion"}</dt><dd>{data.answers?.first} / 5</dd><dt>{data.condition === "appraisal" ? "Current capacity" : "Activity allocation"}</dt><dd>{data.answers?.second} / 5</dd><dt>Intended delegation</dt><dd>{data.answers?.delegation} / 5</dd><dt>Planned assistance</dt><dd>{data.answers?.assistance || "Not selected"}</dd></dl></>}{data.selectedText && <blockquote>{data.selectedText}</blockquote>}{event.type === "ai_handoff" && <p>Destination: genai.eduhk.hk</p>}{event.type === "draft_saved" && <Button variant="outline" onClick={() => setVersion({ text: data.text || "", label: date(event.created) })}>View version {data.revision}</Button>}</article>; })}</div></section></div><div className="review-footer"><span>Most recent 1,000 events · read-only review</span><Button variant="outline" onClick={download}><Download />Export session</Button></div>
  </DialogContent></Dialog>;
}
export default function Teacher({ initialData }: { initialData: TeacherData }) {
  const [data, setData] = useState(initialData);
  const [tab, setTab] = useState("students");
  const [editing, setEditing] = useState<SourceSet | null>(null);
  const [review, setReview] = useState<Review | null>(null);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [studentFilter, setStudentFilter] = useState("all");
  useEffect(() => {
    const context = (document as Document & { modelContext?: { registerTool: (tool: unknown, options: { signal: AbortSignal }) => void } }).modelContext;
    if (!context) return;
    const lifecycle = new AbortController();
    try { void Promise.resolve(context.registerTool({ name: "get_teacher_overview", description: "Read counts from the signed-in AWARE teacher dashboard. Does not edit student assignments or return writing text.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async (input: unknown) => { if (!input || typeof input !== "object" || Object.keys(input).length || Array.isArray(input)) throw new Error("Provide an empty object."); return { students: data.students.length, sourceSets: data.materials.length, writingSessions: data.sessions.length, aiHandoffs: data.aiRequests }; } }, { signal: lifecycle.signal })).catch(() => {}); } catch { /* The teacher interface works without WebMCP. */ }
    return () => lifecycle.abort();
  }, [data]);
  async function refresh() { const response = await fetch("/api/platform"); const result = await response.json() as { teacher: TeacherData; error?: string }; if (!response.ok || !result.teacher) throw new Error(result.error || "Please sign in again."); setData(result.teacher); }
  async function refreshClick() { setBusy(true); setError(""); try { await refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function openSession(id: string) { setBusy(true); setError(""); try { setReview(await api<Review>("teacher.session", { sessionId: id })); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function signout() { try { await api("logout"); window.location.reload(); } catch (e) { setError((e as Error).message); } }
  return <div className="workspace teacher-workspace condition-appraisal"><header className="app-header"><Logo compact /><nav aria-label="Teacher navigation">{[{ id: "students", label: "Students" }, { id: "materials", label: "Materials" }, { id: "records", label: "Writing & AI records" }].map(item => <Button variant="ghost" key={item.id} className={tab === item.id ? "nav-active" : ""} onClick={() => setTab(item.id)}>{item.label}</Button>)}</nav><div className="account"><span className="teacher-badge">Teacher</span><span>Nicole</span><Button variant="ghost" className="icon-button" aria-label="Sign out" onClick={signout}><LogOut /></Button></div></header>
    <main className="teacher-main"><div className="teacher-heading"><div><p className="eyebrow muted">STUDY MANAGEMENT</p><h1>{tab === "students" ? "A considered learning space." : tab === "materials" ? "Reading materials" : "Writing & AI records"}</h1><p>{tab === "students" ? "Manage students, reading tasks, and interaction conditions." : tab === "materials" ? "Prepare the two sources students will read before writing." : "Review saved writing, checkpoint decisions, and AI handoffs."}</p></div><Button variant="outline" disabled={busy} onClick={refreshClick}><RefreshCw />Refresh</Button></div>
      {error && <p className="error-message" role="alert">{error}</p>}
      <div className="teacher-stats"><div><Users /><span>Students</span><strong>{data.students.length}</strong></div><div><BookOpen /><span>Source sets</span><strong>{data.materials.length}</strong></div><div><FileText /><span>Writing sessions</span><strong>{data.sessions.length}</strong></div><div><ArrowUpRight /><span>AI handoffs</span><strong>{data.aiRequests}</strong></div></div>
      {tab === "students" && <section className="teacher-section"><div className="teacher-section-title"><h2>Student assignments</h2><p>Each student sees only their assigned source set.</p></div><div className="assignment-list">{data.students.map(student => <StudentRow key={`${student.username}-${student.condition}-${student.source_set_id}`} student={student} materials={data.materials} saved={refresh} />)}</div><p className="teacher-footnote">Assignments apply to the next new session. In-progress sessions retain their original sources and condition to protect the study record.</p></section>}
      {tab === "materials" && <section className="teacher-section"><div className="teacher-section-title"><div><h2>Source library</h2><p>Two contrasting texts for each writing task.</p></div><Button className="condition-button" onClick={() => setEditing({ ...emptyMaterial })}><Plus />New source set</Button></div><div className="material-list">{data.materials.map(material => <article key={material.id}><div className="material-icon"><BookOpen /></div><div><p className="eyebrow muted">{material.isDemo ? "DEMONSTRATION" : "STUDY MATERIALS"}</p><h3>{material.title}</h3><p>Source A · {words(material.aBody)} words <span>Source B · {words(material.bBody)} words</span></p></div><Button variant="outline" onClick={() => setEditing(material)}><Pencil />Edit</Button></article>)}</div></section>}
      {tab === "records" && <section className="teacher-section"><div className="teacher-section-title"><div><h2>Session records</h2><p>Refresh to see students’ latest saved work.</p></div><Choice label="Filter records by student" value={studentFilter} change={setStudentFilter} options={[{ value: "all", label: "All students" }, ...data.students.map(s => ({ value: s.username, label: s.username }))]} /></div><p className="teacher-boundary">External AI conversations are not available in this version. AI records contain AWARE clicks, checkpoint answers, and handoff times only.</p><div className="teacher-records">{data.sessions.filter(s => studentFilter === "all" || s.username === studentFilter).map(session => <article key={session.id}><span className="user-initial">{session.username.toUpperCase()}</span><div><h3>{session.task_title || "Predictive learning analytics"}</h3><p>{session.username} · {date(session.updated)} · {session.status === "active" ? "In progress" : "Completed"}</p></div><span className={`condition-tag condition-${session.condition || "appraisal"}`}><i />{session.condition ? conditions[session.condition].label : "Initial demo"}</span><Button variant="outline" disabled={busy} onClick={() => openSession(session.id)}>Review <ChevronRight /></Button></article>)}{data.sessions.length === 0 && <p className="empty-events">Writing sessions will appear here after students begin.</p>}</div></section>}
    </main>{editing && <MaterialEditor material={editing} onClose={() => setEditing(null)} onSaved={refresh} />}{review && <SessionReview review={review} onClose={() => setReview(null)} />}
  </div>;
}
